// packages/react/src/ark-empty.tsx
import type { ArkEmptyStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkEmptyProps = PropsWithChildren<
  ArkEmptyStyleOptions & {
    /** Titulo (h3). */
    heading?: string;
    /** Texto abaixo do titulo. */
    description?: string;
    className?: string;
  }
>;

export function ArkEmpty(props: ArkEmptyProps): React.JSX.Element {
  const { children, className, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | undefined> = {
    ...rest,
    class: className
  };

  return createElement("ark-empty", attrs, children);
}

// packages/angular/src/ark-empty.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import type { ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-empty-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-empty
    [attr.testid]="testid"
    [attr.heading]="heading"
    [attr.description]="description"
    [attr.theme]="theme">
    <ng-content></ng-content>
  </ark-empty>`
})
export class ArkEmptyComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Título (h3). */
  @Input() heading: string | undefined;
  /** Texto abaixo do título. */
  @Input() description: string | undefined;
  @Input() theme: ArkTheme = "auto";
}
