// packages/react/src/ark-copy-button.tsx
import type { ArkCopyButtonStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, type PropsWithChildren, useEffect, useRef } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkCopyButtonProps = PropsWithChildren<
  ArkCopyButtonStyleOptions & {
    /** Texto a copiar. */
    value?: string;
    /** id de um elemento (vira o atributo for): copia o value de inputs/textareas ou o textContent. */
    htmlFor?: string;
    /** Duracao do feedback "copiado" em ms. Padrao: 1500. */
    feedbackMs?: number;
    disabled?: boolean;
    className?: string;
    onCopy?: (event: CustomEvent<{ value: string }>) => void;
  }
>;

export function ArkCopyButton(props: ArkCopyButtonProps): React.JSX.Element {
  const {
    children,
    className,
    htmlFor,
    feedbackMs,
    textColor,
    localeJson,
    loading,
    iconOnly,
    fullWidth,
    disabled,
    onCopy,
    ...rest
  } = props;
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onCopy) return;

    const handler = (event: Event) => onCopy(event as CustomEvent<{ value: string }>);
    el.addEventListener("ark-copy", handler);
    return () => el.removeEventListener("ark-copy", handler);
  }, [onCopy]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    for: htmlFor,
    "feedback-ms": feedbackMs === undefined ? undefined : String(feedbackMs),
    "text-color": textColor,
    "locale-json": localeJson,
    loading: loading ? "" : undefined,
    disabled: disabled ? "" : undefined,
    "icon-only": iconOnly ? "" : undefined,
    "full-width": fullWidth ? "" : undefined
  };

  return createElement("ark-copy-button", attrs, children);
}

// packages/angular/src/ark-copy-button.component.ts
import {
  type AfterViewInit,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  type ElementRef,
  EventEmitter,
  Input,
  type OnDestroy,
  Output,
  ViewChild
} from "@angular/core";
import type { ArkButtonVariant, ArkIntent, ArkLang, ArkRounded, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-copy-button-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-copy-button
    #button
    [attr.testid]="testid"
    [attr.value]="value"
    [attr.for]="for"
    [attr.feedback-ms]="feedbackMs"
    [attr.variant]="variant"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    [attr.rounded]="rounded"
    [attr.disabled]="disabled ? '' : null"
    [attr.loading]="loading ? '' : null"
    [attr.icon-only]="iconOnly ? '' : null"
    [attr.full-width]="fullWidth ? '' : null"
    [attr.color]="color"
    [attr.text-color]="textColor"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson">
    <ng-content></ng-content>
  </ark-copy-button>`
})
export class ArkCopyButtonComponent implements AfterViewInit, OnDestroy {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Texto a copiar. */
  @Input() value: string | undefined;
  /** id de um elemento: copia o value de inputs/textareas ou o textContent. */
  @Input() for: string | undefined;
  /** Duração do feedback "copiado" em ms. Padrão: 1500. */
  @Input() feedbackMs: number | undefined;
  @Input() variant: ArkButtonVariant = "primary";
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  @Input() rounded: ArkRounded = "md";
  @Input() disabled = false;
  @Input() loading = false;
  @Input() iconOnly = false;
  @Input() fullWidth = false;
  @Input() color: string | undefined;
  @Input() textColor: string | undefined;
  @Input() lang: ArkLang | undefined;
  @Input() localeJson: string | undefined;
  @Output() arkCopy = new EventEmitter<CustomEvent<{ value: string }>>();

  @ViewChild("button", { static: false }) buttonRef!: ElementRef<HTMLElement>;

  private copyHandler = (event: Event) => this.arkCopy.emit(event as CustomEvent<{ value: string }>);

  ngAfterViewInit(): void {
    this.buttonRef?.nativeElement?.addEventListener("ark-copy", this.copyHandler);
  }

  ngOnDestroy(): void {
    this.buttonRef?.nativeElement?.removeEventListener("ark-copy", this.copyHandler);
  }
}
