// packages/react/src/ark-mark.tsx
import type { ArkMarkStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkMarkProps = ArkMarkStyleOptions & {
  /** Com rotulo a marca vira role="img" nomeado; sem ele e decorativa (aria-hidden). */
  label?: string;
  className?: string;
};

export function ArkMark(props: ArkMarkProps): React.JSX.Element {
  const { className, size, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | undefined> = {
    ...rest,
    class: className,
    size: size === undefined ? undefined : String(size)
  };

  return createElement("ark-mark", attrs);
}

// packages/angular/src/ark-mark.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import type { ArkMarkShape, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-mark-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-mark
    [attr.testid]="testid"
    [attr.shape]="shape"
    [attr.color]="color"
    [attr.size]="size"
    [attr.label]="label"
    [attr.theme]="theme">
  </ark-mark>`
})
export class ArkMarkComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Forma desenhada. Padrão: "circle". */
  @Input() shape: ArkMarkShape = "circle";
  /** Cor CSS da forma. Padrão: a cor do texto ao redor. */
  @Input() color: string | undefined;
  /** Lado do SVG: número em px ou comprimento CSS. Padrão: 16. */
  @Input() size: number | string | undefined;
  /** Com rótulo a marca vira role="img" nomeado; sem ele é decorativa (aria-hidden). */
  @Input() label: string | undefined;
  @Input() theme: ArkTheme = "auto";
}
