// packages/react/src/ark-calendar.tsx
import type { ArkCalendarEvent, ArkCalendarStyleOptions, ArkDatepickerLang, ArkLocale } from "@tooark/core";
import React, { createElement, useCallback, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkCalendarProps = ArkCalendarStyleOptions & {
  lang?: ArkDatepickerLang;
  localeJson?: Partial<ArkLocale>;
  value?: string;
  min?: string;
  max?: string;
  onChange?: (detail: { value: string | null; date: Date | null; events: ArkCalendarEvent[] }) => void;
  className?: string;
};

export function ArkCalendar(props: ArkCalendarProps): React.JSX.Element {
  const {
    lang,
    localeJson,
    theme,
    intent,
    accentColor,
    value,
    min,
    max,
    onChange,
    className,
    testid,
    events,
    eventDisplay
  } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const handleChange = useCallback(
    (e: Event) => {
      if (onChange) {
        onChange((e as CustomEvent).detail);
      }
    },
    [onChange]
  );

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    el.addEventListener("ark-change", handleChange);
    return () => el.removeEventListener("ark-change", handleChange);
  }, [handleChange]);

  const attrs: Record<string, string | undefined> = {
    lang,
    theme,
    intent,
    value,
    min,
    max,
    testid,
    class: className,
    "accent-color": accentColor,
    "locale-json": localeJson ? JSON.stringify(localeJson) : undefined,
    events: events ? JSON.stringify(events) : undefined,
    "event-display": eventDisplay
  };

  return createElement("ark-calendar", { ...attrs, ref });
}

// packages/angular/src/ark-calendar.component.ts
import { AfterViewInit, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild } from "@angular/core";
import type { ArkCalendarEvent, ArkDatepickerLang, ArkIntent, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-calendar-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-calendar
    #calendar
    [attr.testid]="testid"
    [attr.lang]="lang"
    [attr.locale-json]="localeJsonStr"
    [attr.theme]="theme"
    [attr.intent]="intent"
    [attr.accent-color]="accentColor"
    [attr.value]="value"
    [attr.min]="min"
    [attr.max]="max"
    [attr.events]="eventsStr"
    [attr.event-display]="eventDisplay">
  </ark-calendar>`
})
export class ArkCalendarComponent implements AfterViewInit, OnDestroy {
  @Input() testid: string | undefined;
  @Input() lang: ArkDatepickerLang = "en";
  @Input() localeJson: Record<string, unknown> | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() intent: ArkIntent = "primary";
  @Input() accentColor: string | undefined;
  @Input() value: string | undefined;
  @Input() min: string | undefined;
  @Input() max: string | undefined;
  @Input() events: ArkCalendarEvent[] | undefined;
  @Input() eventDisplay: "dots" | "count" | "list" | undefined;
  @Output() arkChange = new EventEmitter<{ value: string | null; date: Date | null; events: ArkCalendarEvent[] }>();

  @ViewChild("calendar", { static: false }) calendarRef!: ElementRef<HTMLElement>;

  private handler = (e: Event) => this.arkChange.emit((e as CustomEvent).detail);

  get eventsStr(): string | undefined {
    return this.events ? JSON.stringify(this.events) : undefined;
  }

  get localeJsonStr(): string | undefined {
    return this.localeJson ? JSON.stringify(this.localeJson) : undefined;
  }

  ngAfterViewInit(): void {
    this.calendarRef?.nativeElement?.addEventListener("ark-change", this.handler);
  }

  ngOnDestroy(): void {
    this.calendarRef?.nativeElement?.removeEventListener("ark-change", this.handler);
  }
}
