// packages/react/src/ark-button.tsx
import React, { createElement, PropsWithChildren, useEffect } from "react";

import type { ArkButtonStyleOptions, ArkButtonType } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkButtonProps = PropsWithChildren<
  ArkButtonStyleOptions & {
    type?: ArkButtonType;
    disabled?: boolean;
    className?: string;
  }
>;

export function ArkButton(props: ArkButtonProps): React.JSX.Element {
  const { children, className, textColor, loading, iconOnly, fullWidth, disabled, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | boolean | undefined> = {
    ...rest,
    class: className,
    "text-color": textColor,
    disabled: disabled ? "" : undefined,
    loading: loading ? "" : undefined,
    "icon-only": iconOnly ? "" : undefined,
    "full-width": fullWidth ? "" : undefined,
  };

  return createElement("ark-button", attrs, children);
}

// packages/angular/src/ark-button.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";
import type { ArkSize, ArkButtonType, ArkButtonVariant, ArkIntent, ArkRounded, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-button-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-button
    [attr.type]="type"
    [attr.disabled]="disabled ? '' : null"
    [attr.loading]="loading ? '' : null"
    [attr.icon-only]="iconOnly ? '' : null"
    [attr.full-width]="fullWidth ? '' : null"
    [attr.variant]="variant"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.rounded]="rounded"
    [attr.href]="href"
    [attr.target]="target"
    [attr.color]="color"
    [attr.text-color]="textColor"
    [attr.size]="size">
    <ng-content></ng-content>
  </ark-button>`
})
export class ArkButtonComponent {
  @Input() type: ArkButtonType = "button";
  @Input() disabled = false;
  @Input() loading = false;
  @Input() iconOnly = false;
  @Input() fullWidth = false;
  @Input() variant: ArkButtonVariant = "primary";
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  @Input() rounded: ArkRounded = "md";
  @Input() href: string | undefined;
  @Input() target: string | undefined;
  @Input() color: string | undefined;
  @Input() textColor: string | undefined;
}
