// packages/react/src/ark-command-palette.tsx
import type { ArkCommandItemStyleOptions, ArkCommandPaletteStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, type PropsWithChildren, useEffect, useRef } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkCommandPaletteProps = PropsWithChildren<
  ArkCommandPaletteStyleOptions & {
    /** Aberta; a saida anima antes de sair do top layer. */
    open?: boolean;
    /** Placeholder e nome do campo de busca. Padrao: a string `search` do idioma. */
    placeholder?: string;
    /** Atalho global: "/", "mod+k" (Ctrl ou Cmd), "ctrl+shift+p"... */
    hotkey?: string;
    /** Filtra localmente pelo label dos itens. */
    filter?: boolean;
    /** Debounce de ark-query em ms. Padrao: 150. */
    queryDelay?: number;
    /** Nome acessivel do dialogo. */
    label?: string;
    /** A pagina continua rolando com a paleta aberta. */
    noScrollLock?: boolean;
    "aria-label"?: string;
    className?: string;
    onSelect?: (event: CustomEvent<{ value: string }>) => void;
    onQuery?: (event: CustomEvent<{ query: string }>) => void;
    onOpen?: (event: CustomEvent) => void;
    onClose?: (event: CustomEvent) => void;
  }
>;

export function ArkCommandPalette(props: ArkCommandPaletteProps): React.JSX.Element {
  const {
    children,
    className,
    open,
    filter,
    queryDelay,
    noScrollLock,
    localeJson,
    onSelect,
    onQuery,
    onOpen,
    onClose,
    ...rest
  } = props;
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleSelect = (event: Event): void => onSelect?.(event as CustomEvent<{ value: string }>);
    const handleQuery = (event: Event): void => onQuery?.(event as CustomEvent<{ query: string }>);
    const handleOpen = (event: Event): void => onOpen?.(event as CustomEvent);
    const handleClose = (event: Event): void => onClose?.(event as CustomEvent);
    el.addEventListener("ark-select", handleSelect);
    el.addEventListener("ark-query", handleQuery);
    el.addEventListener("ark-open", handleOpen);
    el.addEventListener("ark-close", handleClose);
    return () => {
      el.removeEventListener("ark-select", handleSelect);
      el.removeEventListener("ark-query", handleQuery);
      el.removeEventListener("ark-open", handleOpen);
      el.removeEventListener("ark-close", handleClose);
    };
  }, [onSelect, onQuery, onOpen, onClose]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    open: open ? "" : undefined,
    filter: filter ? "" : undefined,
    "no-scroll-lock": noScrollLock ? "" : undefined,
    "query-delay": queryDelay === undefined ? undefined : String(queryDelay),
    "locale-json": localeJson
  };

  return createElement("ark-command-palette", attrs, children);
}

export type ArkCommandItemProps = PropsWithChildren<
  ArkCommandItemStyleOptions & {
    value: string;
    /** Secao em que a paleta lista o item. */
    group?: string;
    /** Texto do filtro e nome da opcao. Padrao: o texto dos filhos sem slot. */
    label?: string;
    disabled?: boolean;
    className?: string;
  }
>;

export function ArkCommandItem(props: ArkCommandItemProps): React.JSX.Element {
  const { children, className, disabled, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | undefined> = {
    ...rest,
    class: className,
    disabled: disabled ? "" : undefined
  };

  return createElement("ark-command-item", attrs, children);
}

// packages/angular/src/ark-command-palette.component.ts
import {
  type AfterViewInit,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  type ElementRef,
  EventEmitter,
  Input,
  type OnDestroy,
  Output,
  ViewChild
} from "@angular/core";
import type { ArkLang, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-command-palette-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-command-palette
    #palette
    [attr.testid]="testid"
    [attr.open]="open ? '' : null"
    [attr.placeholder]="placeholder"
    [attr.hotkey]="hotkey"
    [attr.no-scroll-lock]="noScrollLock ? '' : null"
    [attr.filter]="filter ? '' : null"
    [attr.query-delay]="queryDelay"
    [attr.label]="label"
    [attr.theme]="theme"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson"
    [attr.aria-label]="ariaLabel">
    <ng-content></ng-content>
  </ark-command-palette>`
})
export class ArkCommandPaletteComponent implements AfterViewInit, OnDestroy {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Aberta; a saída anima antes de sair do top layer. */
  @Input() open = false;
  /** Placeholder e nome do campo de busca. Padrão: a string `search` do idioma. */
  @Input() placeholder: string | undefined;
  /** Atalho global: "/", "mod+k" (Ctrl ou Cmd), "ctrl+shift+p"... */
  @Input() hotkey: string | undefined;
  /** A página continua rolando com a paleta aberta. */
  @Input() noScrollLock = false;
  /** Filtra localmente pelo label dos itens. */
  @Input() filter = false;
  /** Debounce de ark-query em ms. Padrão: 150. */
  @Input() queryDelay: number | undefined;
  /** Nome acessível do diálogo. */
  @Input() label: string | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() lang: ArkLang | undefined;
  @Input() localeJson: string | undefined;
  @Input() ariaLabel: string | undefined;
  @Output() arkSelect = new EventEmitter<CustomEvent<{ value: string }>>();
  @Output() arkQuery = new EventEmitter<CustomEvent<{ query: string }>>();
  @Output() arkOpen = new EventEmitter<CustomEvent>();
  @Output() arkClose = new EventEmitter<CustomEvent>();

  @ViewChild("palette", { static: false }) paletteRef!: ElementRef<HTMLElement>;

  private selectHandler = (event: Event) => this.arkSelect.emit(event as CustomEvent<{ value: string }>);
  private queryHandler = (event: Event) => this.arkQuery.emit(event as CustomEvent<{ query: string }>);
  private openHandler = (event: Event) => this.arkOpen.emit(event as CustomEvent);
  private closeHandler = (event: Event) => this.arkClose.emit(event as CustomEvent);

  ngAfterViewInit(): void {
    const el = this.paletteRef?.nativeElement;
    el?.addEventListener("ark-select", this.selectHandler);
    el?.addEventListener("ark-query", this.queryHandler);
    el?.addEventListener("ark-open", this.openHandler);
    el?.addEventListener("ark-close", this.closeHandler);
  }

  ngOnDestroy(): void {
    const el = this.paletteRef?.nativeElement;
    el?.removeEventListener("ark-select", this.selectHandler);
    el?.removeEventListener("ark-query", this.queryHandler);
    el?.removeEventListener("ark-open", this.openHandler);
    el?.removeEventListener("ark-close", this.closeHandler);
  }
}

@Component({
  selector: "ark-command-item-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-command-item
    [attr.testid]="testid"
    [attr.value]="value"
    [attr.group]="group"
    [attr.label]="label"
    [attr.disabled]="disabled ? '' : null">
    <ng-content></ng-content>
  </ark-command-item>`
})
export class ArkCommandItemComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  @Input() value = "";
  /** Seção em que a paleta lista o item. */
  @Input() group: string | undefined;
  /** Texto do filtro e nome da opção. Padrão: o texto projetado sem slot. */
  @Input() label: string | undefined;
  @Input() disabled = false;
}
