// packages/react/src/ark-skeleton.tsx
import type { ArkSkeletonStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkSkeletonProps = PropsWithChildren<
  ArkSkeletonStyleOptions & {
    /** Numero de barras; acima de 1 troca o bloco por barras em coluna. Padrao: 1. */
    rows?: number;
    /** Liga o brilho que varre (opt-in; para sob movimento reduzido). */
    animated?: boolean;
    className?: string;
    style?: React.CSSProperties;
  }
>;

export function ArkSkeleton(props: ArkSkeletonProps): React.JSX.Element {
  const { children, className, rows, animated, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | undefined | React.CSSProperties> = {
    ...rest,
    class: className,
    rows: rows === undefined ? undefined : String(rows),
    animated: animated ? "" : undefined
  };

  return createElement("ark-skeleton", attrs, children);
}

// packages/angular/src/ark-skeleton.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import type { ArkRounded, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-skeleton-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-skeleton
    [attr.testid]="testid"
    [attr.rows]="rows"
    [attr.animated]="animated ? '' : null"
    [attr.rounded]="rounded"
    [attr.theme]="theme">
    <ng-content></ng-content>
  </ark-skeleton>`
})
export class ArkSkeletonComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Número de barras; acima de 1 troca o bloco por barras em coluna. Padrão: 1. */
  @Input() rows: number | undefined;
  /** Liga o brilho que varre (opt-in; para sob movimento reduzido). */
  @Input() animated = false;
  /** Raio dos cantos. Padrão: o do preset (lg). */
  @Input() rounded: ArkRounded | undefined;
  @Input() theme: ArkTheme = "auto";
}
