// packages/react/src/ark-input.tsx
import type { ArkInputStyleOptions, ArkLang } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkInputProps = PropsWithChildren<
  ArkInputStyleOptions & {
    type?: string;
    label?: string;
    placeholder?: string;
    value?: string;
    name?: string;
    helper?: string;
    error?: boolean;
    errorMessage?: string;
    disabled?: boolean;
    required?: boolean;
    readonly?: boolean;
    /** Com type="password", botao de mostrar/ocultar na ponta direita. */
    reveal?: boolean;
    lang?: ArkLang;
    localeJson?: string;
    autocomplete?: string;
    autofocus?: boolean;
    inputmode?: string;
    maxlength?: number;
    minlength?: number;
    pattern?: string;
    min?: string | number;
    max?: string | number;
    step?: string | number;
    spellcheck?: boolean;
    "aria-label"?: string;
    className?: string;
    onInput?: (event: Event) => void;
    onChange?: (event: Event) => void;
  }
>;

// Atributo do custom element: string ou ausente.
function attr(value: string | number | undefined): string | undefined {
  return value === undefined ? undefined : String(value);
}

export function ArkInput(props: ArkInputProps): React.JSX.Element {
  const {
    children,
    className,
    errorMessage,
    error,
    disabled,
    required,
    readonly,
    reveal,
    localeJson,
    autofocus,
    maxlength,
    minlength,
    min,
    max,
    step,
    spellcheck,
    onInput,
    onChange,
    ...rest
  } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleInput = (event: Event): void => onInput?.(event);
    const handleChange = (event: Event): void => onChange?.(event);
    el.addEventListener("input", handleInput);
    el.addEventListener("change", handleChange);
    return () => {
      el.removeEventListener("input", handleInput);
      el.removeEventListener("change", handleChange);
    };
  }, [onInput, onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    "error-message": errorMessage,
    "locale-json": localeJson,
    error: error ? "" : undefined,
    disabled: disabled ? "" : undefined,
    required: required ? "" : undefined,
    readonly: readonly ? "" : undefined,
    reveal: reveal ? "" : undefined,
    autofocus: autofocus ? "" : undefined,
    maxlength: attr(maxlength),
    minlength: attr(minlength),
    min: attr(min),
    max: attr(max),
    step: attr(step),
    spellcheck: spellcheck === undefined ? undefined : spellcheck ? "true" : "false"
  };

  return createElement("ark-input", attrs, children);
}

// packages/angular/src/ark-input.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, Input, inject } from "@angular/core";
import type { ArkIntent, ArkLang, ArkRounded, ArkSize, ArkTheme } from "@tooark/core";
import type { ArkInput as ArkInputElement } from "@tooark/web-components";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-input-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-input
    [attr.testid]="testid"
    [attr.type]="type"
    [attr.label]="label"
    [attr.placeholder]="placeholder"
    [attr.value]="value"
    [attr.name]="name"
    [attr.size]="size"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.rounded]="rounded"
    [attr.helper]="helper"
    [attr.error]="error ? '' : null"
    [attr.error-message]="errorMessage"
    [attr.disabled]="disabled ? '' : null"
    [attr.required]="required ? '' : null"
    [attr.readonly]="readonly ? '' : null"
    [attr.reveal]="reveal ? '' : null"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson"
    [attr.autocomplete]="autocomplete"
    [attr.autofocus]="autofocus ? '' : null"
    [attr.inputmode]="inputmode"
    [attr.maxlength]="maxlength"
    [attr.minlength]="minlength"
    [attr.pattern]="pattern"
    [attr.min]="min"
    [attr.max]="max"
    [attr.step]="step"
    [attr.spellcheck]="spellcheckAttr"
    [attr.aria-label]="ariaLabel">
    <ng-content></ng-content>
  </ark-input>`
})
export class ArkInputComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);

  /** O `ark-input` que este wrapper renderiza, com os métodos e propriedades do elemento; `null` antes da view. */
  get element(): ArkInputElement | null {
    return this.host.nativeElement.querySelector<ArkInputElement>(":scope > ark-input");
  }

  @Input() testid: string | undefined;
  @Input() type = "text";
  @Input() label: string | undefined;
  @Input() placeholder: string | undefined;
  @Input() value: string | undefined;
  @Input() name: string | undefined;
  @Input() size: ArkSize = "md";
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() rounded: ArkRounded = "lg";
  @Input() helper: string | undefined;
  @Input() error = false;
  @Input() errorMessage: string | undefined;
  @Input() disabled = false;
  @Input() required = false;
  @Input() readonly = false;
  /** Com type="password", botão de mostrar/ocultar na ponta direita. */
  @Input() reveal = false;
  @Input() lang: ArkLang | undefined;
  @Input() localeJson: string | undefined;
  @Input() autocomplete: string | undefined;
  @Input() autofocus = false;
  @Input() inputmode: string | undefined;
  @Input() maxlength: number | undefined;
  @Input() minlength: number | undefined;
  @Input() pattern: string | undefined;
  @Input() min: string | number | undefined;
  @Input() max: string | number | undefined;
  @Input() step: string | number | undefined;
  @Input() spellcheck: boolean | undefined;
  @Input() ariaLabel: string | undefined;

  get spellcheckAttr(): string | null {
    return this.spellcheck === undefined ? null : String(this.spellcheck);
  }
}
