// packages/angular/src/ark-checkbox.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EventEmitter, Input, inject, Output } from "@angular/core";
import type { ArkIntent, ArkSize, ArkTheme } from "@tooark/core";
import type { ArkCheckbox as ArkCheckboxElement } from "@tooark/web-components";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-checkbox-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-checkbox
    [attr.testid]="testid"
    [attr.aria-label]="ariaLabel"
    [attr.checked]="checked ? '' : null"
    [attr.indeterminate]="indeterminate ? '' : null"
    [attr.disabled]="disabled ? '' : null"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    [attr.name]="name"
    [attr.value]="value"
    [attr.label]="label"
    [attr.helper]="helper"
    (change)="onChange($event)">
    <ng-content></ng-content>
  </ark-checkbox>`
})
export class ArkCheckboxComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);

  /** O `ark-checkbox` que este wrapper renderiza, com os métodos e propriedades do elemento; `null` antes da view. */
  get element(): ArkCheckboxElement | null {
    return this.host.nativeElement.querySelector<ArkCheckboxElement>(":scope > ark-checkbox");
  }

  @Input() testid: string | undefined;
  /** Nome acessível, repassado ao elemento (o aria-label no wrapper ficaria no host errado). */
  @Input() ariaLabel: string | undefined;
  @Input() checked = false;
  /** Estado misto (aria-checked="mixed", traço); o próximo clique o limpa. */
  @Input() indeterminate = false;
  @Input() disabled = false;
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  /** Nome no formulário (submete `value` quando marcado). */
  @Input() name: string | undefined;
  /** Valor submetido quando marcado. Padrão: "on". */
  @Input() value: string | undefined;
  /** Rótulo próprio (<label for>); sem ele use aria-label ou o conteúdo projetado como rótulo livre. */
  @Input() label: string | undefined;
  /** Dica abaixo do rótulo, ligada ao controle por aria-describedby. */
  @Input() helper: string | undefined;
  @Output() changed = new EventEmitter<CustomEvent<{ checked: boolean }>>();

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ checked: boolean }>);
  }
}

// packages/react/src/ark-checkbox.tsx
import type { ArkCheckboxStyleOptions } from "@tooark/core";
import type { ArkCheckbox as ArkCheckboxElement } from "@tooark/web-components";
import React, { createElement, forwardRef, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";
import { useForwardedRef } from "./use-forwarded-ref.js";

export type ArkCheckboxProps = PropsWithChildren<
  ArkCheckboxStyleOptions & {
    disabled?: boolean;
    /** Nome no formulario (submete `value` quando marcado). */
    name?: string;
    /** Valor submetido quando marcado. Padrao: "on". */
    value?: string;
    /** Rotulo proprio (<label for>); sem ele use aria-label ou filhos como rotulo livre. */
    label?: string;
    /** Dica abaixo do rotulo, ligada ao controle por aria-describedby. */
    helper?: string;
    className?: string;
    onChange?: (event: CustomEvent<{ checked: boolean }>) => void;
  }
>;

export const ArkCheckbox = forwardRef<ArkCheckboxElement, ArkCheckboxProps>(
  function ArkCheckbox(props, forwardedRef): React.JSX.Element {
    const { children, className, checked, indeterminate, disabled, onChange, ...rest } = props;
    const [ref, setRef] = useForwardedRef<ArkCheckboxElement>(forwardedRef);

    useEffect(() => {
      ensureTooarkComponentsRegistered();
    }, []);

    useEffect(() => {
      const el = ref.current;
      if (!el || !onChange) return;

      const handler = (event: Event) => onChange(event as CustomEvent<{ checked: boolean }>);
      el.addEventListener("change", handler);
      return () => el.removeEventListener("change", handler);
    }, [ref, onChange]);

    const attrs: Record<string, string | undefined | React.Ref<ArkCheckboxElement>> = {
      ...rest,
      ref: setRef,
      class: className,
      checked: checked ? "" : undefined,
      indeterminate: indeterminate ? "" : undefined,
      disabled: disabled ? "" : undefined
    };

    return createElement("ark-checkbox", attrs, children);
  }
);
