// packages/angular/src/ark-scheduler.component.ts
import {
  type AfterViewInit,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  type ElementRef,
  EventEmitter,
  Input,
  type OnDestroy,
  Output,
  ViewChild
} from "@angular/core";
import type { ArkDatepickerLang, ArkIntent, ArkSchedulerEvent, ArkSchedulerView, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-scheduler-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-scheduler
    #scheduler
    [attr.testid]="testid"
    [attr.view]="view"
    [attr.date]="date"
    [attr.events]="eventsStr"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson"
    [attr.theme]="theme"
    [attr.intent]="intent"
    [attr.views]="views"
    [attr.hour-start]="hourStart"
    [attr.hour-end]="hourEnd"
    [attr.slot-minutes]="slotMinutes"
    [attr.hours-format]="hoursFormat">
  </ark-scheduler>`
})
export class ArkSchedulerComponent implements AfterViewInit, OnDestroy {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  @Input() view: ArkSchedulerView = "week";
  @Input() date: string | undefined;
  @Input() events: ArkSchedulerEvent[] | undefined;
  @Input() lang: ArkDatepickerLang = "en";
  /** JSON com strings próprias, mesclado sobre o inglês, quando lang é "custom". */
  @Input() localeJson: string | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() intent: ArkIntent = "primary";
  @Input() views: string | undefined;
  @Input() hourStart: number | undefined;
  @Input() hourEnd: number | undefined;
  @Input() slotMinutes: number | undefined;
  @Input() hoursFormat: "24" | "12" | undefined;

  @Output() arkEventClick = new EventEmitter<{ event: ArkSchedulerEvent; id: string | null }>();
  @Output() arkSlotClick = new EventEmitter<{ start: string; end: string; allDay: boolean }>();
  @Output() arkViewChange = new EventEmitter<{ view: string }>();
  @Output() arkRangeChange = new EventEmitter<{ start: string; end: string; view: string }>();

  @ViewChild("scheduler", { static: false }) schedulerRef!: ElementRef<HTMLElement>;

  private eventClickHandler = (e: Event) => this.arkEventClick.emit((e as CustomEvent).detail);
  private slotClickHandler = (e: Event) => this.arkSlotClick.emit((e as CustomEvent).detail);
  private viewChangeHandler = (e: Event) => this.arkViewChange.emit((e as CustomEvent).detail);
  private rangeChangeHandler = (e: Event) => this.arkRangeChange.emit((e as CustomEvent).detail);

  get eventsStr(): string | undefined {
    return this.events ? JSON.stringify(this.events) : undefined;
  }

  ngAfterViewInit(): void {
    const el = this.schedulerRef?.nativeElement;
    if (!el) return;
    el.addEventListener("ark-event-click", this.eventClickHandler);
    el.addEventListener("ark-slot-click", this.slotClickHandler);
    el.addEventListener("ark-view-change", this.viewChangeHandler);
    el.addEventListener("ark-range-change", this.rangeChangeHandler);
  }

  ngOnDestroy(): void {
    const el = this.schedulerRef?.nativeElement;
    if (!el) return;
    el.removeEventListener("ark-event-click", this.eventClickHandler);
    el.removeEventListener("ark-slot-click", this.slotClickHandler);
    el.removeEventListener("ark-view-change", this.viewChangeHandler);
    el.removeEventListener("ark-range-change", this.rangeChangeHandler);
  }
}

// packages/react/src/ark-scheduler.tsx
import type { ArkDatepickerLang, ArkSchedulerEvent, ArkSchedulerStyleOptions } from "@tooark/core";
import React, { createElement, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkSchedulerProps = ArkSchedulerStyleOptions & {
  lang?: ArkDatepickerLang;
  /** JSON com strings próprias, mesclado sobre o inglês, quando lang é "custom". */
  localeJson?: string;
  className?: string;
  onEventClick?: (detail: { event: ArkSchedulerEvent; id: string | null }) => void;
  onSlotClick?: (detail: { start: string; end: string; allDay: boolean }) => void;
  onViewChange?: (detail: { view: string }) => void;
  onRangeChange?: (detail: { start: string; end: string; view: string }) => void;
};

export function ArkScheduler(props: ArkSchedulerProps): React.JSX.Element {
  const {
    className,
    events,
    hourStart,
    hourEnd,
    slotMinutes,
    hoursFormat,
    localeJson,
    onEventClick,
    onSlotClick,
    onViewChange,
    onRangeChange,
    ...rest
  } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handlers: Array<[string, EventListener]> = [];
    function bind<T>(name: string, handler?: (detail: T) => void): void {
      if (!handler) return;
      const listener: EventListener = (event) => handler((event as CustomEvent<T>).detail);
      el!.addEventListener(name, listener);
      handlers.push([name, listener]);
    }

    bind("ark-event-click", onEventClick);
    bind("ark-slot-click", onSlotClick);
    bind("ark-view-change", onViewChange);
    bind("ark-range-change", onRangeChange);

    return () => {
      for (const [name, listener] of handlers) {
        el.removeEventListener(name, listener);
      }
    };
  }, [onEventClick, onSlotClick, onViewChange, onRangeChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    events: events ? JSON.stringify(events) : undefined,
    "hour-start": hourStart !== undefined ? String(hourStart) : undefined,
    "hour-end": hourEnd !== undefined ? String(hourEnd) : undefined,
    "slot-minutes": slotMinutes !== undefined ? String(slotMinutes) : undefined,
    "hours-format": hoursFormat,
    "locale-json": localeJson
  };

  return createElement("ark-scheduler", attrs);
}
