// packages/angular/src/ark-datepicker.component.ts
import { AfterViewInit, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild } from "@angular/core";
import type { ArkCalendarEvent, ArkDatepickerLang, ArkIntent, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-datepicker-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-datepicker 
    #picker
    [attr.testid]="testid"
    [attr.lang]="lang"
    [attr.locale-json]="localeJsonStr"
    [attr.theme]="theme"
    [attr.intent]="intent"
    [attr.accent-color]="accentColor"
    [attr.value]="value"
    [attr.min]="min"
    [attr.max]="max"
    [attr.mode]="mode"
    [attr.input]="input ? '' : null"
    [attr.seconds]="seconds ? '' : null"
    [attr.placeholder]="placeholder"
    [attr.name]="name"
    [attr.format]="format"
    [attr.disabled]="disabled ? '' : null"
    [attr.events]="eventsStr"
    [attr.event-display]="eventDisplay"
    [attr.step-minutes]="stepMinutes"
    [attr.hours-format]="hoursFormat">
  </ark-datepicker>`
})
export class ArkDatepickerComponent implements AfterViewInit, OnDestroy {
  @Input() testid: string | undefined;
  @Input() lang: ArkDatepickerLang = "en";
  @Input() localeJson: Record<string, unknown> | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() intent: ArkIntent = "primary";
  @Input() accentColor: string | undefined;
  @Input() value: string | undefined;
  @Input() min: string | undefined;
  @Input() max: string | undefined;
  @Input() mode: "datetime" | "date" | "time" = "datetime";
  @Input() input = false;
  @Input() seconds = false;
  @Input() placeholder: string | undefined;
  @Input() name: string | undefined;
  @Input() format: string | undefined;
  @Input() disabled = false;
  @Input() events: ArkCalendarEvent[] | undefined;
  @Input() eventDisplay: "dots" | "count" | "list" | undefined;
  @Input() stepMinutes: number | undefined;
  @Input() hoursFormat: "24" | "12" | undefined;

  @Output() arkChange = new EventEmitter<{ value: string | null; date: Date | null }>();

  @ViewChild("picker", { static: false }) pickerRef!: ElementRef<HTMLElement>;

  private handler = (e: Event) => this.arkChange.emit((e as CustomEvent).detail);

  get eventsStr(): string | undefined {
    return this.events ? JSON.stringify(this.events) : undefined;
  }

  get localeJsonStr(): string | undefined {
    return this.localeJson ? JSON.stringify(this.localeJson) : undefined;
  }

  ngAfterViewInit(): void {
    this.pickerRef?.nativeElement?.addEventListener("ark-change", this.handler);
  }

  ngOnDestroy(): void {
    this.pickerRef?.nativeElement?.removeEventListener("ark-change", this.handler);
  }
}

// packages/react/src/ark-datepicker.tsx
import React, { useCallback, useEffect } from "react";
import type { ArkDatepickerLang, ArkDatepickerLocale, ArkDatepickerStyleOptions } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkDatepickerProps = ArkDatepickerStyleOptions & {
  lang?: ArkDatepickerLang;
  localeJson?: Partial<ArkDatepickerLocale>;
  value?: string;
  min?: string;
  max?: string;
  onChange?: (detail: { value: string | null; date: Date | null }) => void;
  className?: string;
};

export function ArkDatepicker(props: ArkDatepickerProps): React.JSX.Element {
  const { lang, localeJson, theme, intent, accentColor, value, min, max, onChange, className, testid, mode, input, placeholder, name, format, seconds, disabled, events, eventDisplay, stepMinutes, hoursFormat } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const handleChange = useCallback(
    (e: Event) => {
      if (onChange) {
        const detail = (e as CustomEvent).detail;
        onChange(detail);
      }
    },
    [onChange]
  );

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    el.addEventListener("ark-change", handleChange);
    return () => el.removeEventListener("ark-change", handleChange);
  }, [handleChange]);

  const attrs: Record<string, string | undefined> = {
    lang,
    theme,
    intent,
    value,
    min,
    max,
    testid,
    mode,
    placeholder,
    name,
    format,
    input: input ? "" : undefined,
    seconds: seconds ? "" : undefined,
    disabled: disabled ? "" : undefined,
    class: className,
    "accent-color": accentColor,
    "locale-json": localeJson ? JSON.stringify(localeJson) : undefined,
    events: events ? JSON.stringify(events) : undefined,
    "event-display": eventDisplay,
    "step-minutes": stepMinutes !== undefined ? String(stepMinutes) : undefined,
    "hours-format": hoursFormat
  };

  return React.createElement("ark-datepicker", { ...attrs, ref });
}
