// packages/angular/src/ark-file-input.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import type { ArkIntent, ArkLang, ArkRounded, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-file-input-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-file-input
    [attr.testid]="testid"
    [attr.accept]="accept"
    [attr.multiple]="multiple ? '' : null"
    [attr.label]="label"
    [attr.helper]="helper"
    [attr.error-message]="errorMessage"
    [attr.disabled]="disabled ? '' : null"
    [attr.required]="required ? '' : null"
    [attr.name]="name"
    [attr.intent]="intent"
    [attr.size]="size"
    [attr.rounded]="rounded"
    [attr.theme]="theme"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson"
    (change)="onChange($event)">
  </ark-file-input>`
})
export class ArkFileInputComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Tipos aceitos pelo seletor nativo (accept). */
  @Input() accept: string | undefined;
  /** Aceita vários arquivos; sem ele o drop fica com o primeiro. */
  @Input() multiple = false;
  /** Rótulo do campo (label for o input oculto; nomeia o botão junto do texto dele). */
  @Input() label: string | undefined;
  @Input() helper: string | undefined;
  /** Mensagem de erro; liga aria-invalid e a borda de erro. */
  @Input() errorMessage: string | undefined;
  @Input() disabled = false;
  @Input() required = false;
  /** Nome no formulário (input nativo oculto). */
  @Input() name: string | undefined;
  @Input() intent: ArkIntent = "primary";
  @Input() size: ArkSize = "md";
  /** Cantos da zona de soltar. Padrão: "lg". */
  @Input() rounded: ArkRounded | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() lang: ArkLang | undefined;
  @Input() localeJson: string | undefined;
  /** Arquivos escolhidos ou soltos: detail.files é um array de File. */
  @Output() changed = new EventEmitter<CustomEvent<{ files: File[] }>>();

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ files: File[] }>);
  }
}

// packages/react/src/ark-file-input.tsx
import type { ArkFileInputStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, useEffect, useRef } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkFileInputProps = ArkFileInputStyleOptions & {
  /** Tipos aceitos pelo seletor nativo (accept). */
  accept?: string;
  /** Aceita varios arquivos; sem ele o drop fica com o primeiro. */
  multiple?: boolean;
  /** Rotulo do campo (label for o input oculto; nomeia o botao junto do texto dele). */
  label?: string;
  helper?: string;
  /** Mensagem de erro; liga aria-invalid e a borda de erro. */
  errorMessage?: string;
  disabled?: boolean;
  required?: boolean;
  /** Nome no formulario (input nativo oculto). */
  name?: string;
  className?: string;
  /** Arquivos escolhidos ou soltos: detail.files e um array de File. */
  onChange?: (event: CustomEvent<{ files: File[] }>) => void;
};

export function ArkFileInput(props: ArkFileInputProps): React.JSX.Element {
  const { className, multiple, errorMessage, disabled, required, localeJson, onChange, ...rest } = props;
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ files: File[] }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    multiple: multiple ? "" : undefined,
    "error-message": errorMessage,
    disabled: disabled ? "" : undefined,
    required: required ? "" : undefined,
    "locale-json": localeJson
  };

  return createElement("ark-file-input", attrs);
}
