// packages/angular/src/ark-toaster.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import type { ArkTheme, ArkToastPosition } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-toaster-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-toaster
    [attr.testid]="testid"
    [attr.theme]="theme"
    [attr.position]="position"
    [attr.max-visible]="maxVisible"
    [attr.duration]="duration"
    [attr.rich-colors]="richColors ? '' : null"
    [attr.close-button]="closeButton ? null : 'false'">
  </ark-toaster>`
})
export class ArkToasterComponent {
  @Input() testid: string | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() position: ArkToastPosition = "bottom-right";
  @Input() richColors = false;
  @Input() closeButton = true;
  @Input() maxVisible = 4;
  @Input() duration = 4000;
}

// packages/react/src/ark-toaster.tsx
import type { ArkToasterStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkToasterProps = ArkToasterStyleOptions & {
  className?: string;
};

export function ArkToaster(props: ArkToasterProps): React.JSX.Element {
  const { theme, position, richColors, closeButton, maxVisible, duration, className, testid } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const attrs: Record<string, string | number | boolean | undefined> = {
    theme,
    position,
    "max-visible": maxVisible,
    duration,
    testid,
    class: className,
    "rich-colors": richColors ? true : undefined,
    "close-button": closeButton === undefined ? undefined : closeButton ? true : "false"
  };

  return createElement("ark-toaster", attrs);
}
