// packages/angular/src/ark-color-swatches.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import type { ArkColorSwatch, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-color-swatches-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-color-swatches
    [attr.testid]="testid"
    [attr.value]="value"
    [attr.colors]="colorsJson"
    [attr.label]="label"
    [attr.disabled]="disabled ? '' : null"
    [attr.size]="size"
    [attr.theme]="theme"
    (change)="onChange($event)">
  </ark-color-swatches>`
})
export class ArkColorSwatchesComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Cor selecionada (o value da amostra). */
  @Input() value: string | undefined;
  /** Amostras { name, value }[]; vão como JSON no atributo. */
  @Input() colors: ArkColorSwatch[] | undefined;
  /** Nome acessível do radiogroup. */
  @Input() label: string | undefined;
  @Input() disabled = false;
  @Input() size: ArkSize = "md";
  @Input() theme: ArkTheme = "auto";
  /** Seleção mudou pelo usuário: detail.value é a cor. */
  @Output() changed = new EventEmitter<CustomEvent<{ value: string }>>();

  get colorsJson(): string | null {
    return this.colors ? JSON.stringify(this.colors) : null;
  }

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ value: string }>);
  }
}

// packages/react/src/ark-color-swatches.tsx
import type { ArkColorSwatch, ArkColorSwatchesStyleOptions } from "@tooark/core";
import type React from "react";
import { createElement, useEffect, useRef } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkColorSwatchesProps = ArkColorSwatchesStyleOptions & {
  /** Cor selecionada (o value da amostra). */
  value?: string;
  /** Amostras { name, value }[]; vai como JSON no atributo. */
  colors?: ArkColorSwatch[];
  /** Nome acessivel do radiogroup. */
  label?: string;
  disabled?: boolean;
  className?: string;
  /** Selecao mudou pelo usuario: detail.value e a cor. */
  onChange?: (event: CustomEvent<{ value: string }>) => void;
};

export function ArkColorSwatches(props: ArkColorSwatchesProps): React.JSX.Element {
  const { className, colors, disabled, onChange, ...rest } = props;
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ value: string }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    colors: colors ? JSON.stringify(colors) : undefined,
    disabled: disabled ? "" : undefined
  };

  return createElement("ark-color-swatches", attrs);
}
