// packages/angular/src/ark-switch.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";
import type { ArkIntent, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-switch-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-switch
    [attr.checked]="checked ? '' : null"
    [attr.disabled]="disabled ? '' : null"
    [attr.labels]="labels ? '' : null"
    [attr.icons]="icons ? '' : null"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    [attr.color]="color"
    [attr.name]="name"
    [attr.value]="value"
    [attr.label]="label"
    [attr.label-on]="labelOn"
    [attr.label-off]="labelOff"
    (change)="onChange($event)">
  </ark-switch>`
})
export class ArkSwitchComponent {
  @Input() checked = false;
  @Input() disabled = false;
  @Input() labels = false;
  @Input() icons = false;
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  @Input() color: string | undefined;
  @Input() name: string | undefined;
  @Input() value: string | undefined;
  @Input() label: string | undefined;
  @Input() labelOn: string | undefined;
  @Input() labelOff: string | undefined;
  @Output() changed = new EventEmitter<CustomEvent<{ checked: boolean }>>();

  onChange (event: Event): void {
    this.changed.emit(event as CustomEvent<{ checked: boolean }>);
  }
}

// packages/react/src/ark-switch.tsx
import type { ArkSwitchStyleOptions } from "@tooark/core";
import React, { createElement, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkSwitchProps = ArkSwitchStyleOptions & {
  disabled?: boolean;
  name?: string;
  value?: string;
  label?: string;
  className?: string;
  onChange?: (event: CustomEvent<{ checked: boolean }>) => void;
};

export function ArkSwitch(props: ArkSwitchProps): React.JSX.Element {
  const { className, checked, labels, labelOn, labelOff, icons, disabled, onChange, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ checked: boolean }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | boolean | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    checked: checked ? "" : undefined,
    disabled: disabled ? "" : undefined,
    labels: labels ? "" : undefined,
    icons: icons ? "" : undefined,
    "label-on": labelOn,
    "label-off": labelOff
  };

  return createElement("ark-switch", attrs);
}
