// packages/angular/src/ark-shape-picker.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import type { ArkLang, ArkMarkShape, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-shape-picker-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-shape-picker
    [attr.testid]="testid"
    [attr.aria-label]="ariaLabel"
    [attr.value]="value"
    [attr.shapes]="shapesAttr"
    [attr.color]="color"
    [attr.label]="label"
    [attr.disabled]="disabled ? '' : null"
    [attr.size]="size"
    [attr.theme]="theme"
    [attr.lang]="lang"
    [attr.locale-json]="localeJson"
    (change)="onChange($event)">
  </ark-shape-picker>`
})
export class ArkShapePickerComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  /** Nome acessível, repassado ao elemento (o aria-label no wrapper ficaria no host errado). */
  @Input() ariaLabel: string | undefined;
  /** Forma selecionada. */
  @Input() value: ArkMarkShape | undefined;
  /** Formas oferecidas, na ordem, ou "all" para as dez. Padrão: as seis originais. */
  @Input() shapes: ArkMarkShape[] | "all" | undefined;
  /** Cor CSS em que as formas são desenhadas. Padrão: a cor do texto ao redor. */
  @Input() color: string | undefined;
  /** Nome acessível do radiogroup. */
  @Input() label: string | undefined;
  @Input() disabled = false;
  @Input() size: ArkSize = "md";
  @Input() theme: ArkTheme = "auto";
  @Input() lang: ArkLang | undefined;
  @Input() localeJson: string | undefined;
  /** Seleção mudou pelo usuário: detail.value é a forma. */
  @Output() changed = new EventEmitter<CustomEvent<{ value: ArkMarkShape }>>();

  get shapesAttr(): string | null {
    if (Array.isArray(this.shapes)) return this.shapes.length > 0 ? this.shapes.join(",") : null;
    return this.shapes ?? null;
  }

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ value: ArkMarkShape }>);
  }
}

// packages/react/src/ark-shape-picker.tsx
import type { ArkMarkShape, ArkShapePickerStyleOptions } from "@tooark/core";
import type { ArkShapePicker as ArkShapePickerElement } from "@tooark/web-components";
import type React from "react";
import { createElement, forwardRef, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";
import { useForwardedRef } from "./use-forwarded-ref.js";

export type ArkShapePickerProps = ArkShapePickerStyleOptions & {
  /** Forma selecionada. */
  value?: ArkMarkShape;
  /** Formas oferecidas, na ordem, ou "all" para as dez. Padrao: as seis originais. */
  shapes?: ArkMarkShape[] | "all";
  /** Nome acessivel do radiogroup. */
  label?: string;
  disabled?: boolean;
  className?: string;
  /** Selecao mudou pelo usuario: detail.value e a forma. */
  onChange?: (event: CustomEvent<{ value: ArkMarkShape }>) => void;
};

export const ArkShapePicker = forwardRef<ArkShapePickerElement, ArkShapePickerProps>(
  function ArkShapePicker(props, forwardedRef): React.JSX.Element {
    const { className, disabled, shapes, localeJson, onChange, ...rest } = props;
    const [ref, setRef] = useForwardedRef<ArkShapePickerElement>(forwardedRef);

    useEffect(() => {
      ensureTooarkComponentsRegistered();
    }, []);

    useEffect(() => {
      const el = ref.current;
      if (!el || !onChange) return;

      const handler = (event: Event) => onChange(event as CustomEvent<{ value: ArkMarkShape }>);
      el.addEventListener("change", handler);
      return () => el.removeEventListener("change", handler);
    }, [ref, onChange]);

    const attrs: Record<string, string | undefined | React.Ref<ArkShapePickerElement>> = {
      ...rest,
      ref: setRef,
      class: className,
      disabled: disabled ? "" : undefined,
      shapes: Array.isArray(shapes) ? (shapes.length > 0 ? shapes.join(",") : undefined) : shapes,
      "locale-json": localeJson
    };

    return createElement("ark-shape-picker", attrs);
  }
);
