// packages/angular/src/ark-carousel.component.ts
import { AfterViewInit, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild } from "@angular/core";
import type { ArkCarouselSnap, ArkIntent, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-carousel-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-carousel
    #carousel
    [attr.testid]="testid"
    [attr.theme]="theme"
    [attr.intent]="intent"
    [attr.accent-color]="accentColor"
    [attr.slides-per-view]="slidesPerView"
    [attr.gap]="gap"
    [attr.start-index]="startIndex"
    [attr.autoplay-delay]="autoplayDelay"
    [attr.snap]="snap"
    [attr.loop]="loop ? '' : null"
    [attr.autoplay]="autoplay ? '' : null"
    [attr.drag-free]="dragFree ? '' : null"
    [attr.show-dots]="showDots ? null : 'false'"
    [attr.show-arrows]="showArrows ? null : 'false'">
    <ng-content></ng-content>
  </ark-carousel>`
})
export class ArkCarouselComponent implements AfterViewInit, OnDestroy {
  @Input() testid: string | undefined;
  @Input() theme: ArkTheme = "auto";
  @Input() intent: ArkIntent = "primary";
  @Input() accentColor: string | undefined;
  @Input() slidesPerView = 1;
  @Input() gap = 12;
  @Input() startIndex = 0;
  @Input() loop = false;
  @Input() autoplay = false;
  @Input() autoplayDelay = 4200;
  @Input() showDots = true;
  @Input() showArrows = true;
  @Input() dragFree = false;
  @Input() snap: ArkCarouselSnap = "mandatory";

  @Output() arkSlideChange = new EventEmitter<{ index: number }>();

  @ViewChild("carousel", { static: false }) carouselRef!: ElementRef<HTMLElement>;

  private handler = (e: Event) => this.arkSlideChange.emit((e as CustomEvent).detail);

  ngAfterViewInit(): void {
    this.carouselRef?.nativeElement?.addEventListener("ark-slide-change", this.handler);
  }

  ngOnDestroy(): void {
    this.carouselRef?.nativeElement?.removeEventListener("ark-slide-change", this.handler);
  }
}

// packages/react/src/ark-carousel.tsx
import type { ArkCarouselSnap, ArkCarouselStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useCallback, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkCarouselProps = PropsWithChildren<
  ArkCarouselStyleOptions & {
    snap?: ArkCarouselSnap;
    onSlideChange?: (detail: { index: number }) => void;
    className?: string;
  }
>;

export function ArkCarousel(props: ArkCarouselProps): React.JSX.Element {
  const {
    children,
    theme,
    intent,
    accentColor,
    slidesPerView,
    gap,
    startIndex,
    loop,
    autoplay,
    autoplayDelay,
    showDots,
    showArrows,
    dragFree,
    snap,
    onSlideChange,
    className,
    testid
  } = props;

  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const handleSlideChange = useCallback(
    (event: Event) => {
      if (onSlideChange) {
        onSlideChange((event as CustomEvent).detail);
      }
    },
    [onSlideChange]
  );

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    el.addEventListener("ark-slide-change", handleSlideChange);
    return () => el.removeEventListener("ark-slide-change", handleSlideChange);
  }, [handleSlideChange]);

  const attrs: Record<string, string | number | boolean | undefined> = {
    theme,
    intent,
    "accent-color": accentColor,
    "slides-per-view": slidesPerView,
    gap,
    "start-index": startIndex,
    "autoplay-delay": autoplayDelay,
    snap,
    testid,
    class: className,
    loop: loop ? true : undefined,
    autoplay: autoplay ? true : undefined,
    "drag-free": dragFree ? true : undefined,
    "show-dots": showDots === undefined ? undefined : showDots ? true : "false",
    "show-arrows": showArrows === undefined ? undefined : showArrows ? true : "false"
  };

  return createElement("ark-carousel", { ...attrs, ref }, children);
}
