// packages/angular/src/ark-radio.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import type { ArkIntent, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-radio-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-radio
    [attr.testid]="testid"
    [attr.checked]="checked ? '' : null"
    [attr.disabled]="disabled ? '' : null"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    [attr.name]="name"
    [attr.value]="value"
    [attr.label]="label"
    (change)="onChange($event)">
    <ng-content></ng-content>
  </ark-radio>`
})
export class ArkRadioComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  @Input() checked = false;
  @Input() disabled = false;
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  /** Nome do grupo: agrupa no formulário e para setas/roving tabindex. */
  @Input() name: string | undefined;
  /** Valor submetido e publicado em `change` quando marcado. Padrão: "on". */
  @Input() value: string | undefined;
  /** Rótulo próprio (<label for>); sem ele use aria-label ou o conteúdo projetado como rótulo livre. */
  @Input() label: string | undefined;
  /** Dispara só no radio que ganhou a marca. */
  @Output() changed = new EventEmitter<CustomEvent<{ value: string }>>();

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ value: string }>);
  }
}

// packages/react/src/ark-radio.tsx
import type { ArkRadioStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkRadioProps = PropsWithChildren<
  ArkRadioStyleOptions & {
    disabled?: boolean;
    /** Nome do grupo: agrupa no formulario e para setas/roving tabindex. */
    name?: string;
    /** Valor submetido e publicado em `change` quando marcado. Padrao: "on". */
    value?: string;
    /** Rotulo proprio (<label for>); sem ele use aria-label ou filhos como rotulo livre. */
    label?: string;
    className?: string;
    /** Dispara so no radio que ganhou a marca. */
    onChange?: (event: CustomEvent<{ value: string }>) => void;
  }
>;

export function ArkRadio(props: ArkRadioProps): React.JSX.Element {
  const { children, className, checked, disabled, onChange, ...rest } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ value: string }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    checked: checked ? "" : undefined,
    disabled: disabled ? "" : undefined
  };

  return createElement("ark-radio", attrs, children);
}
