// packages/angular/src/ark-toggle.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";
import type { ArkIntent, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-toggle-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-toggle
    [attr.pressed]="pressed ? '' : null"
    [attr.disabled]="disabled ? '' : null"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    [attr.value]="value"
    (change)="onChange($event)">
    <ng-content></ng-content>
  </ark-toggle>`
})
export class ArkToggleComponent {
  @Input() pressed = false;
  @Input() disabled = false;
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() size: ArkSize = "md";
  @Input() value: string | undefined;
  @Output() changed = new EventEmitter<CustomEvent<{ pressed: boolean; value: string }>>();

  onChange (event: Event): void {
    this.changed.emit(event as CustomEvent<{ pressed: boolean; value: string }>);
  }
}

@Component({
  selector: "ark-toggle-group-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-toggle-group
    [attr.value]="value"
    [attr.multiple]="multiple ? '' : null"
    [attr.disabled]="disabled ? '' : null"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.size]="size"
    (change)="onChange($event)">
    <ng-content></ng-content>
  </ark-toggle-group>`
})
export class ArkToggleGroupComponent {
  @Input() value: string | undefined;
  @Input() multiple = false;
  @Input() disabled = false;
  @Input() intent: ArkIntent | undefined;
  @Input() theme: ArkTheme | undefined;
  @Input() size: ArkSize | undefined;
  @Output() changed = new EventEmitter<CustomEvent<{ value?: string; values?: string[] }>>();

  onChange (event: Event): void {
    this.changed.emit(event as CustomEvent<{ value?: string; values?: string[] }>);
  }
}

// packages/react/src/ark-toggle.tsx
import React, { createElement, PropsWithChildren, useEffect } from "react";

import type { ArkToggleGroupStyleOptions, ArkToggleStyleOptions } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkToggleProps = PropsWithChildren<
  ArkToggleStyleOptions & {
    disabled?: boolean;
    className?: string;
    onChange?: (event: CustomEvent<{ pressed: boolean; value: string }>) => void;
  }
>;

export function ArkToggle(props: ArkToggleProps): React.JSX.Element {
  const { children, className, pressed, disabled, onChange, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ pressed: boolean; value: string }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | boolean | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    pressed: pressed ? "" : undefined,
    disabled: disabled ? "" : undefined,
  };

  return createElement("ark-toggle", attrs, children);
}

export type ArkToggleGroupProps = PropsWithChildren<
  ArkToggleGroupStyleOptions & {
    disabled?: boolean;
    className?: string;
    onChange?: (event: CustomEvent<{ value?: string; values?: string[] }>) => void;
  }
>;

export function ArkToggleGroup(props: ArkToggleGroupProps): React.JSX.Element {
  const { children, className, multiple, disabled, onChange, ...rest } = props;

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event) => onChange(event as CustomEvent<{ value?: string; values?: string[] }>);
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, [onChange]);

  const attrs: Record<string, string | boolean | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    multiple: multiple ? "" : undefined,
    disabled: disabled ? "" : undefined,
  };

  return createElement("ark-toggle-group", attrs, children);
}
