// packages/angular/src/ark-textarea.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import type { ArkIntent, ArkRounded, ArkSize, ArkTextareaResize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-textarea-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-textarea
    [attr.testid]="testid"
    [attr.label]="label"
    [attr.placeholder]="placeholder"
    [attr.value]="value"
    [attr.name]="name"
    [attr.rows]="rows"
    [attr.autosize]="autosize ? '' : null"
    [attr.monospace]="monospace ? '' : null"
    [attr.resize]="resize"
    [attr.size]="size"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.rounded]="rounded"
    [attr.helper]="helper"
    [attr.error]="error ? '' : null"
    [attr.error-message]="errorMessage"
    [attr.disabled]="disabled ? '' : null"
    [attr.required]="required ? '' : null"
    [attr.readonly]="readonly ? '' : null"
    [attr.autocomplete]="autocomplete"
    [attr.autofocus]="autofocus ? '' : null"
    [attr.maxlength]="maxlength"
    [attr.minlength]="minlength"
    [attr.spellcheck]="spellcheckAttr"
    [attr.wrap]="wrap"
    [attr.aria-label]="ariaLabel">
    <ng-content></ng-content>
  </ark-textarea>`
})
export class ArkTextareaComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  @Input() label: string | undefined;
  @Input() placeholder: string | undefined;
  @Input() value: string | undefined;
  @Input() name: string | undefined;
  /** Linhas visíveis iniciais. Padrão: 3. */
  @Input() rows: number | undefined;
  /** Cresce com o conteúdo (field-sizing nativo, fallback por JS). */
  @Input() autosize = false;
  /** Fonte monoespaçada, para código e dados. */
  @Input() monospace = false;
  @Input() resize: ArkTextareaResize = "vertical";
  @Input() size: ArkSize = "md";
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() rounded: ArkRounded = "lg";
  @Input() helper: string | undefined;
  @Input() error = false;
  @Input() errorMessage: string | undefined;
  @Input() disabled = false;
  @Input() required = false;
  @Input() readonly = false;
  @Input() autocomplete: string | undefined;
  @Input() autofocus = false;
  @Input() maxlength: number | undefined;
  @Input() minlength: number | undefined;
  @Input() spellcheck: boolean | undefined;
  /** Quebra de linha do valor enviado (soft/hard) ou sem quebra visual (off), como no <textarea>. */
  @Input() wrap: "soft" | "hard" | "off" | undefined;
  @Input() ariaLabel: string | undefined;

  get spellcheckAttr(): string | null {
    return this.spellcheck === undefined ? null : String(this.spellcheck);
  }
}

// packages/react/src/ark-textarea.tsx
import type { ArkTextareaResize, ArkTextareaStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkTextareaProps = PropsWithChildren<
  ArkTextareaStyleOptions & {
    label?: string;
    placeholder?: string;
    value?: string;
    name?: string;
    /** Linhas visiveis iniciais. Padrao: 3. */
    rows?: number;
    /** Cresce com o conteudo (field-sizing nativo, fallback por JS). */
    autosize?: boolean;
    /** Fonte monoespacada, para codigo e dados. */
    monospace?: boolean;
    /** Direcoes de redimensionamento pelo usuario. Padrao: "vertical". */
    resize?: ArkTextareaResize;
    helper?: string;
    error?: boolean;
    errorMessage?: string;
    disabled?: boolean;
    required?: boolean;
    readonly?: boolean;
    autocomplete?: string;
    autofocus?: boolean;
    maxlength?: number;
    minlength?: number;
    spellcheck?: boolean;
    /** Quebra de linha do valor enviado (soft/hard) ou sem quebra visual (off), como no <textarea>. */
    wrap?: "soft" | "hard" | "off";
    "aria-label"?: string;
    className?: string;
    onInput?: (event: Event) => void;
    onChange?: (event: Event) => void;
  }
>;

// Atributo do custom element: string ou ausente.
function attr(value: string | number | undefined): string | undefined {
  return value === undefined ? undefined : String(value);
}

export function ArkTextarea(props: ArkTextareaProps): React.JSX.Element {
  const {
    children,
    className,
    rows,
    autosize,
    monospace,
    errorMessage,
    error,
    disabled,
    required,
    readonly,
    autofocus,
    maxlength,
    minlength,
    spellcheck,
    onInput,
    onChange,
    ...rest
  } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleInput = (event: Event): void => onInput?.(event);
    const handleChange = (event: Event): void => onChange?.(event);
    el.addEventListener("input", handleInput);
    el.addEventListener("change", handleChange);
    return () => {
      el.removeEventListener("input", handleInput);
      el.removeEventListener("change", handleChange);
    };
  }, [onInput, onChange]);

  const attrs: Record<string, string | boolean | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    rows: attr(rows),
    autosize: autosize ? "" : undefined,
    monospace: monospace ? "" : undefined,
    "error-message": errorMessage,
    error: error ? "" : undefined,
    disabled: disabled ? "" : undefined,
    required: required ? "" : undefined,
    readonly: readonly ? "" : undefined,
    // Booleanos, não strings: o React 19 grava nas propriedades nativas autofocus/spellcheck do host (onde "" seria
    // false e "false" seria true), e o React 18 os serializa no atributo.
    autofocus: autofocus || undefined,
    maxlength: attr(maxlength),
    minlength: attr(minlength),
    spellcheck
  };

  return createElement("ark-textarea", attrs, children);
}
