// packages/angular/src/ark-clock.component.ts
import { AfterViewInit, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild } from "@angular/core";
import type { ArkDatepickerLang, ArkIntent, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

ensureTooarkComponentsRegistered();

@Component({
  selector: "ark-clock-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-clock
    #clock
    [attr.testid]="testid"
    [attr.value]="value"
    [attr.lang]="lang"
    [attr.theme]="theme"
    [attr.intent]="intent"
    [attr.seconds]="seconds ? '' : null"
    [attr.step-minutes]="stepMinutes"
    [attr.hours-format]="hoursFormat">
  </ark-clock>`
})
export class ArkClockComponent implements AfterViewInit, OnDestroy {
  @Input() testid: string | undefined;
  @Input() value: string | undefined;
  @Input() lang: ArkDatepickerLang = "en";
  @Input() theme: ArkTheme = "auto";
  @Input() intent: ArkIntent = "primary";
  @Input() seconds = false;
  @Input() stepMinutes: number | undefined;
  @Input() hoursFormat: "24" | "12" = "24";
  @Output() arkChange = new EventEmitter<{ value: string }>();

  @ViewChild("clock", { static: false }) clockRef!: ElementRef<HTMLElement>;

  private handler = (e: Event) => this.arkChange.emit((e as CustomEvent).detail);

  ngAfterViewInit(): void {
    this.clockRef?.nativeElement?.addEventListener("ark-change", this.handler);
  }

  ngOnDestroy(): void {
    this.clockRef?.nativeElement?.removeEventListener("ark-change", this.handler);
  }
}

// packages/react/src/ark-clock.tsx
import type { ArkClockStyleOptions, ArkDatepickerLang } from "@tooark/core";
import React, { createElement, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register.js";

export type ArkClockProps = ArkClockStyleOptions & {
  value?: string;
  lang?: ArkDatepickerLang;
  className?: string;
  onChange?: (detail: { value: string }) => void;
};

export function ArkClock(props: ArkClockProps): React.JSX.Element {
  const { className, seconds, stepMinutes, hoursFormat, onChange, ...rest } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || !onChange) return;

    const handler = (event: Event): void => onChange((event as CustomEvent).detail);
    el.addEventListener("ark-change", handler);
    return () => el.removeEventListener("ark-change", handler);
  }, [onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    seconds: seconds ? "" : undefined,
    "step-minutes": stepMinutes !== undefined ? String(stepMinutes) : undefined,
    "hours-format": hoursFormat
  };

  return createElement("ark-clock", attrs);
}
