// packages/angular/src/ark-select.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import type { ArkIntent, ArkRounded, ArkSelectOption, ArkSize, ArkTheme } from "@tooark/core";
import { ensureTooarkComponentsRegistered } from "./register";

@Component({
  selector: "ark-select-wrapper",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
  <ark-select
    [attr.testid]="testid"
    [attr.label]="label"
    [attr.placeholder]="placeholder"
    [attr.options]="optionsStr"
    [attr.value]="value"
    [attr.name]="name"
    [attr.size]="size"
    [attr.intent]="intent"
    [attr.theme]="theme"
    [attr.rounded]="rounded"
    [attr.helper]="helper"
    [attr.error]="error ? '' : null"
    [attr.error-message]="errorMessage"
    [attr.disabled]="disabled ? '' : null"
    [attr.required]="required ? '' : null"
    (change)="onChange($event)">
    <ng-content></ng-content>
  </ark-select>`
})
export class ArkSelectComponent {
  constructor() {
    ensureTooarkComponentsRegistered();
  }

  @Input() testid: string | undefined;
  @Input() label: string | undefined;
  @Input() placeholder: string | undefined;
  @Input() options: ArkSelectOption[] | undefined;
  @Input() value: string | undefined;
  @Input() name: string | undefined;
  @Input() size: ArkSize = "md";
  @Input() intent: ArkIntent = "primary";
  @Input() theme: ArkTheme = "auto";
  @Input() rounded: ArkRounded = "lg";
  @Input() helper: string | undefined;
  @Input() error = false;
  @Input() errorMessage: string | undefined;
  @Input() disabled = false;
  @Input() required = false;
  @Output() changed = new EventEmitter<CustomEvent<{ value: string }>>();

  get optionsStr(): string | undefined {
    return this.options ? JSON.stringify(this.options) : undefined;
  }

  onChange(event: Event): void {
    this.changed.emit(event as CustomEvent<{ value: string }>);
  }
}

// packages/react/src/ark-select.tsx
import type { ArkSelectOption, ArkSelectStyleOptions } from "@tooark/core";
import React, { createElement, type PropsWithChildren, useEffect } from "react";
import { ensureTooarkComponentsRegistered } from "./register";

export type ArkSelectProps = PropsWithChildren<
  ArkSelectStyleOptions & {
    label?: string;
    placeholder?: string;
    options?: ArkSelectOption[];
    value?: string;
    name?: string;
    helper?: string;
    error?: boolean;
    errorMessage?: string;
    disabled?: boolean;
    required?: boolean;
    className?: string;
    onInput?: (event: Event) => void;
    onChange?: (event: CustomEvent<{ value: string }>) => void;
  }
>;

export function ArkSelect(props: ArkSelectProps): React.JSX.Element {
  const { children, className, options, errorMessage, error, disabled, required, onInput, onChange, ...rest } = props;
  const ref = React.useRef<HTMLElement>(null);

  useEffect(() => {
    ensureTooarkComponentsRegistered();
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleInput = (event: Event): void => onInput?.(event);
    const handleChange = (event: Event): void => onChange?.(event as CustomEvent<{ value: string }>);
    el.addEventListener("input", handleInput);
    el.addEventListener("change", handleChange);
    return () => {
      el.removeEventListener("input", handleInput);
      el.removeEventListener("change", handleChange);
    };
  }, [onInput, onChange]);

  const attrs: Record<string, string | undefined | React.Ref<HTMLElement>> = {
    ...rest,
    ref,
    class: className,
    options: options ? JSON.stringify(options) : undefined,
    "error-message": errorMessage,
    error: error ? "" : undefined,
    disabled: disabled ? "" : undefined,
    required: required ? "" : undefined
  };

  return createElement("ark-select", attrs, children);
}
